name:                calz
version:             0.9.2.0
github:              jez/calz
license:             MIT
author:              Jake Zimmerman
maintainer:          zimmerman.jake@gmail.com
copyright:           2018 Jake Zimmerman

extra-source-files:
- README.md
- LICENSE

# Metadata used when publishing your package
synopsis:            Like the Unix cal program, but better
description:         Please see the README on Github at <https://github.com/jez/calz#readme>
category:            System

ghc-options:
- -Wall
- -Wcompat
- -Wmissing-signatures
- -Werror
- -funbox-strict-fields
# TODO(jez) Remove this option once https://github.com/haskell/cabal/issues/4739 is fixed
- -optP-Wno-nonportable-include-path
- -O2

dependencies:
- base >= 4.7 && < 5
- docopt
- time
- parsec
- monadplus
- split
- mtl
- text
- prettyprinter
- prettyprinter-ansi-terminal


library:
  source-dirs: src

executables:
  calz:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calz

tests:
  calz-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calz
    - hspec
